<a href="https://colab.research.google.com/github/Justyasir123/Handling-of-categorical-values/blob/main/Handling_of_categorical_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('customer.csv')
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

**ORDINAL ENCODING-FOR INDEPENDANT VARIABLE**

In [4]:
from sklearn.preprocessing import OrdinalEncoder

In [6]:
review_order=['Poor','Average','Good']
education_order=['School','UG','PG']
encoder=OrdinalEncoder(categories=[review_order,education_order])

In [8]:
df[['review','education']]=encoder.fit_transform(df[['review','education']])

In [9]:
df.head()

   age  gender  review  education purchased
0   30  Female     1.0        0.0        No
1   68  Female     0.0        1.0        No
2   70  Female     2.0        2.0        No
3   72  Female     2.0        2.0        No
4   16  Female     1.0        1.0        No

**LABEL ENCODING- FOR TARGET VARIABLE**

In [10]:
from sklearn.preprocessing import LabelEncoder

In [13]:
encoder=LabelEncoder()

In [14]:
df['purchased']=encoder.fit_transform(df['purchased'])

In [16]:
df.head()

   age  gender  review  education  purchased
0   30  Female     1.0        0.0          0
1   68  Female     0.0        1.0          0
2   70  Female     2.0        2.0          0
3   72  Female     2.0        2.0          0
4   16  Female     1.0        1.0          0

In [18]:
df1=pd.read_csv('cars.csv')
df1.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

**ONE HOT ENCODING USING PANDAS**

In [61]:
df_new=pd.get_dummies(df1[['fuel','owner']]).astype('int')
df_new

,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,0,1,0,0,1,0,0,0,0
1,0,1,0,0,0,0,1,0,0
2,0,0,0,1,0,0,0,0,1
3,0,1,0,0,1,0,0,0,0
4,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
8123,0,0,0,1,1,0,0,0,0
8124,0,1,0,0,0,1,0,0,0
8125,0,1,0,0,1,0,0,0,0
8126,0,1,0,0,1,0,0,0,0
8127,0,1,0,0,1,0,0,0,0

In [64]:
df_old=df1[['brand','km_driven','selling_price']]
df_old

        brand  km_driven  selling_price
0      Maruti     145500         450000
1       Skoda     120000         370000
2       Honda     140000         158000
3     Hyundai     127000         225000
4      Maruti     120000         130000
...       ...        ...            ...
8123  Hyundai     110000         320000
8124  Hyundai     119000         135000
8125   Maruti     120000         382000
8126     Tata      25000         290000
8127     Tata      25000         290000

[8128 rows x 3 columns]

In [65]:
pd.concat([df_old,df_new],axis=1)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

In [46]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype='int64')

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X=df1.drop('selling_price',axis=1)
y=df1['selling_price']

In [49]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [50]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']])
X_test_new=ohe.transform(X_test[['fuel','owner']])

In [51]:
X_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]])

In [54]:
import numpy as np
a=np.hstack((X_train[['brand','km_driven']].values,X_train_new))
a

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], dtype=object)

In [57]:
pd.DataFrame(a)

             0       1  2  3  4  5  6  7  8
0         Tata    2560  0  0  1  0  0  0  0
1        Honda   80000  0  0  1  0  1  0  0
2      Hyundai  150000  1  0  0  1  0  0  0
3       Maruti  120000  1  0  0  0  1  0  0
4       Maruti   25000  0  0  1  0  0  0  0
...        ...     ... .. .. .. .. .. .. ..
6497  Mahindra  120000  1  0  0  0  0  0  0
6498    Maruti   80000  1  0  0  0  1  0  0
6499   Hyundai   35000  0  0  1  0  0  0  0
6500    Maruti   27000  1  0  0  0  0  0  0
6501    Maruti   70000  0  0  1  0  1  0  0

[6502 rows x 9 columns]

In [59]:
num_ohe_features=X_train_new.shape[1]
pd.DataFrame(a,columns=['brand','km_driven'] + ohe.get_feature_names_out().tolist()[:num_ohe_features])

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Tata,2560,0,0,1,0,0,0,0
1,Honda,80000,0,0,1,0,1,0,0
2,Hyundai,150000,1,0,0,1,0,0,0
3,Maruti,120000,1,0,0,0,1,0,0
4,Maruti,25000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
6497,Mahindra,120000,1,0,0,0,0,0,0
6498,Maruti,80000,1,0,0,0,1,0,0
6499,Hyundai,35000,0,0,1,0,0,0,0
6500,Maruti,27000,1,0,0,0,0,0,0
6501,Maruti,70000,0,0,1,0,1,0,0